// Categories
export const GET_ALL_CATEGORIES_SUCCESSFULLY = 'GET_ALL_CATEGORIES_SUCCESSFULLY';
export const GET_ALL_CATEGORIES_FAILED = 'GET_ALL_CATEGORIES_FAILED';

// posts
export const GET_CATEGORY_POSTS_SUCCESSFULLY = 'GET_CATEGORY_POSTS_SUCCESSFULLY';
export const GET_CATEGORY_POSTS_FAILED = 'GET_CATEGORY_POSTS_FAILED';
export const GET_ALL_POSTS_SUCCESSFULLY = 'GET_ALL_POSTS_SUCCESSFULLY';
export const GET_ALL_POSTS_FAILED = 'GET_ALL_POSTS_FAILED';
export const SAVE_POST_SUCCESSFULLY = 'SAVE_POST_SUCCESSFULLY';
export const SAVE_POST_FAILED = 'SAVE_POST_FAILED';
export const GET_POST_SUCCESSFULLY = 'GET_POST_SUCCESSFULLY';
export const GET_POST_FAILED = 'GET_POST_FAILED';
export const VOTE_POST_SUCCESSFULLY = 'VOTE_POST_SUCCESSFULLY';
export const VOTE_POST_FAILED = 'VOTE_POST_FAILED';
export const UPDATE_POST_SUCCESSFULLY = 'UPDATE_POST_SUCCESSFULLY';
export const UPDATE_POST_FAILED = 'UPDATE_POST_FAILED';
export const DELETE_POST_SUCCESSFULLY = 'DELETE_POST_SUCCESSFULLY';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';

// comments
export const GET_POST_COMMENTS_SUCCESSFULLY = 'GET_POST_COMMENTS_SUCCESSFULLY';
export const GET_POST_COMMENTS_FAILED = 'GET_POST_COMMENTS_FAILED';
export const SAVE_COMMENT_SUCCESSFULLY = 'SAVE_COMMENT_SUCCESSFULLY';
export const SAVE_COMMENT_FAILED = 'SAVE_COMMENT_FAILED';
export const GET_COMMENT_SUCCESSFULLY = 'GET_COMMENT_SUCCESSFULLY';
export const GET_COMMENT_FAILED = 'GET_COMMENT_FAILED';
export const VOTE_COMMENT_SUCCESSFULLY = 'VOTE_COMMENT_SUCCESSFULLY';
export const VOTE_COMMENT_FAILED = 'VOTE_COMMENT_FAILED';
export const UPDATE_COMMENT_SUCCESSFULLY = 'UPDATE_COMMENT_SUCCESSFULLY';
export const UPDATE_COMMENT_FAILED = 'UPDATE_COMMENT_FAILED';
export const DELETE_COMMENT_SUCCESSFULLY = 'DELETE_COMMENT_SUCCESSFULLY';
export const DELETE_COMMENT_FAILED = 'DELETE_COMMENT_FAILED';